### ISSUE TITLE
Bootstrap LESS files issues while navigating between apps

### ISSUE THREAD

**Issue by RaviCk57** [CanopyTax/single-spa-angular#100]
Hi, 

Looked at the previous issues related to bootstrap CSS but none of them helped me. Below is my issue.
When I'm in an App1 after logging in. It works great. Everyhting looks perfect. no alignment issues.
But after I go to App2 and then back to App1, the pages look messy. After inspecting it I found out: the .less are adding up and casuing the issue but turns out i have no less files in Node modules > bootstrap > css > dist or in any of the bootstarp files in node modules. 
How do i get rid of those files when I don't have them in my node modules in the first place.

Thanks,
Ravi

**Comment by RaviCk57** [comment]
![issue1](https://user-images.githubusercontent.com/49765088/62330608-cb3a8600-b47e-11e9-9dc0-5f05d04b4655.PNG)

**Comment by joeldenning** [comment]
Only load one version of bootstrap. Do this in the root html file instead of inside of any of the apps. Your code probably has a js import or css import loading the bootstrap files, and you should delete those lines of code in favor of the root html file loading bootstrap
