### ISSUE TITLE
Problem with creating ng8 single-spa

### ISSUE THREAD

**Issue by mzadrozny** [CanopyTax/single-spa-angular#103]
Can you help me with this? https://github.com/mzadrozny/test-spa
 I think i did everything like in documentation, but still cant get this working. I don't get any error in browser or in console, just app.component doesn't render/working :x

I try to make this with this part of documentation

https://single-spa.js.org/docs/ecosystem-angular.html

**Comment by joeldenning** [comment]
Please follow the tutorial at http://single-spa-playground.org/playground, which will help you diagnose many potential problems.

If that doesn't help you get it working, reopen this issue.

**Comment by joeldenning** [comment]
Ah actually I just now saw that you already have tried single-spa-playground in https://github.com/CanopyTax/single-spa-playground/issues/7.

What is the URL that you are trying to download the angular application from? If you go to that url in the browser, does it properly load?

**Comment by varora1406** [comment]
Hey, I tried to add my angular application which is running at localhost to https://single-spa-playground.org/playground. But it failed to load with error
Error: Could not download app -- server didn't respond with javascript code, but with 'text/html; charset=UTF-8'

What is that I am not understanding correctly with playground documentation?

**Comment by joeldenning** [comment]
@varora1406 what url are you attempting to download the angular application from?

**Comment by mzadrozny** [comment]
I find my problem was with wrong single-spa playground configuration, The isseu can be closed now :)
