### ISSUE TITLE
Reloading core portal from app not working 

### ISSUE THREAD

**Issue by rknash18** [CanopyTax/single-spa-angular#104]
I have a SPA portal application with 3 individual apps and I can navigate through each applications with out any issues but when I try to reload the core portal from  individual app its not working.

when I am in app2 and trying to re-load the portal using  this.router.navigateByUrl('/') , the url on the browser changes but the portal not loading. 

setting window.location.href = '/'  working but the problem is I am loosing all the data in local storage.

Portal
     - app1
     - app2
     - app3

**Comment by joeldenning** [comment]
Could you please provide a github repo that demonstrates the problem?

**Comment by alyssonnogueira** [comment]
> Found a solution as work around .. thanks

Could you, tell Us what work around works? I'm with same problem here. Seems the HTML component is not rendering, but the ngOnInit is called, like router is not activate.
