### ISSUE TITLE
Dependency injection with Angular 7 not working

### ISSUE THREAD

**Issue by danutzcodrescu** [CanopyTax/single-spa-angular#11]
Hello,

I have a problem with dependency injection in any component, using angular 7. For instance let's have a look at injecting Router.

angular.app.ts:
```
import { platformBrowserDynamic } from "@angular/platform-browser-dynamic";
import singleSpaAngular from "single-spa-angular";
import mainModule from "./main.module";
import { Router } from "@angular/router";

const ngLifecycles = singleSpaAngular({
  domElementGetter,
  mainModule,
  angularPlatform: platformBrowserDynamic(),
  template: `<ng-form-app />`,
  Router
});

export const bootstrap = [ngLifecycles.bootstrap];

export const mount = [ngLifecycles.mount];

export const unmount = [ngLifecycles.unmount];

function domElementGetter() {
  return document.getElementById("angular-app");
}
```

main.module.ts:
```
import { NgModule } from "@angular/core";
import { BrowserModule } from "@angular/platform-browser";
import { enableProdMode } from "@angular/core";
import { ReactiveFormsModule } from "@angular/forms";
import { RouterModule, Routes } from "@angular/router";
import { NGFormApp } from "./app.component";
import { CreateBookComponent } from "./components/create-book.component";
import { APP_BASE_HREF } from "@angular/common";
import { EditBookComponent } from "./components/edit-book.component";

const routes: Routes = [
  {
    path: "",
    component: CreateBookComponent
  },
  { path: "books/:id/edit", component: EditBookComponent }
];

try {
  enableProdMode();
} catch (err) {
  console.info("EnableProdMode already set");
}

@NgModule({
  imports: [BrowserModule, RouterModule.forRoot(routes), ReactiveFormsModule],
  declarations: [NGFormApp, CreateBookComponent, EditBookComponent],
  bootstrap: [NGFormApp],
  providers: [{ provide: APP_BASE_HREF, useValue: "/" }]
})
export default class MainModule {}
```

edit-book.component.ts:
```
import { Component, Inject, OnInit } from "@angular/core";
import { FormGroup, FormControl } from "@angular/forms";
import template from "./edit-book.component.html";
import { BooksService } from "../../shared/services/books.service";
import { Router } from "@angular/router";

@Component({
  selector: "ng-create-book",
  template
})
export class EditBookComponent implements OnInit {
  formData: FormGroup;
  constructor(private router: Router) {}

  ngOnInit() {
    this.formData = new FormGroup({
      author: new FormControl(""),
      title: new FormControl("")
    });
  }

  onClickSubmit(data: any) {
    // BooksService.createBook(data).then(resp => {
    //   this.formData.reset();
    // });
  }
}
```

Each time when I do any kind of dependency injection I get the following error: `Uncaught Error: Application 'angular' died in status NOT_MOUNTED: Can't resolve all parameters for EditBookComponent: (?).
    at syntaxError (compiler.js:2547)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getDependenciesMetadata (compiler.js:17874)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getTypeMetadata (compiler.js:17767)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNonNormalizedDirectiveMetadata (compiler.js:17386)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getEntryComponentMetadata (compiler.js:17970)
    at compiler.js:17961
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getEntryComponentsFromProvider (compiler.js:17960)
    at compiler.js:17933
    at Array.forEach (<anonymous>)`.

Am I doing something wrong?

It would be very much appreciated if anyone could have a look over my problem!

Thanks!

**Comment by frehner** [comment]
One possibility is to try and use [single-spa-angular-cli](https://github.com/PlaceMe-SAS/single-spa-angular-cli) which appears to have better support for newer versions of Angular.

**Comment by visweswaranr** [comment]
Were you able to fix it @danutzcodrescu ? I have the same error

**Comment by visweswaranr** [comment]
@joeldenning I am also getting the same error now. And it works fine for me in the regular angular builder configuration of webpack.
![image](https://user-images.githubusercontent.com/4468963/81026979-d917a000-8e30-11ea-984b-2284f3b2690d.png)

The only difference between the 2 builders is that for the custom one, I use the zone.js from the parent app. If I comment out the use of any DI, then it all works fine in the child-app. Any idea what I am doing wrong? Thanks!

**Comment by visweswaranr** [comment]
Nevermind, it was the es7 reflect that I needed to import.

**Comment by joeldenning** [comment]
Glad to hear you got it working.
