### ISSUE TITLE
Angular 8 Lazy Load modules

### ISSUE THREAD

**Issue by revenger1986** [CanopyTax/single-spa-angular#116]
Hi, 

I'm trying to use single-spa-angular, but i'm unsure how to use Lazy Loading of Modules. 
In the 'child' application i have this routing

> const routes: Routes = [
  {
    path: 'settings',
    children: [
      {
        path: '',
        loadChildren: () => import('../app/modules/test/test.module').then((m) => m.TestModule),
      },
    ]
  },
  { path: '**', component: EmptyRouteComponent }
];

> 

When I navigate to 'localhost:4200/settings' I see this error in the chrome console.

> ERROR Error: Uncaught (in promise): ChunkLoadError: Loading chunk vendors~app-modules-test-test-module failed.

When I change my routing to use a component then my component is shown correctly. 

Does anyone have any pointers, how I should solve this issue?

**Comment by joeldenning** [comment]
Failing to load webpack chunks is related to [webpack public path](https://webpack.js.org/guides/public-path/#root). See [these single-spa docs](https://single-spa.js.org/docs/faq/#code-splits) for information on how to fix it. Also see https://github.com/joeldenning/systemjs-webpack-interop

**Comment by revenger1986** [comment]
I still didn't manage to resolve my issue. A pointer in the right direction would be much appreciated. 
I was able to set the publicpath, but I'm unsure how to do this

"Set either output.jsonpFunction or output.library to ensure that each app's webpack doesn't collide with other apps' webpack. jsonpFunction is preferred."   (mentioned in the docs of single-spa)

I tried changing the extra-webpack.config like shown below, but it seems to have little effect

`module.exports = (angularWebpackConfig, options) => {
    output: {
    jsonpFunction: 'app1name'
  }
 
  const singleSpaWebpackConfig = singleSpaAngularWebpack(angularWebpackConfig, options)
   return singleSpaWebpackConfig
}`

**Comment by revenger1986** [comment]
For now it looks like I solved my issue with lazy loading. 

in main.single-spa.ts i had to do this (it has to be the first code in the file)

`import { setPublicPath } from 'systemjs-webpack-interop';
setPublicPath('app1');`

and my extra-webpack.config.js now looks like this

`const singleSpaAngularWebpack = require('single-spa-angular/lib/webpack').default

module.exports = (angularWebpackConfig, options) => {
  angularWebpackConfig.output.jsonpFunction = 'app1';
  
  const singleSpaWebpackConfig = singleSpaAngularWebpack(angularWebpackConfig, options)

  // Feel free to modify this webpack config however you'd like to
  return singleSpaWebpackConfig
}`

Thanks for the help!

**Comment by joeldenning** [comment]
👍 glad you figured it out

**Comment by alihasnain-techverx** [comment]
> For now it looks like I solved my issue with lazy loading.
> 
> in main.single-spa.ts i had to do this (it has to be the first code in the file)
> 
> `import { setPublicPath } from 'systemjs-webpack-interop'; setPublicPath('app1');`
> 
> and my extra-webpack.config.js now looks like this
> 
> `const singleSpaAngularWebpack = require('single-spa-angular/lib/webpack').default
> 
> module.exports = (angularWebpackConfig, options) => {
> angularWebpackConfig.output.jsonpFunction = 'app1';
> 
> const singleSpaWebpackConfig = singleSpaAngularWebpack(angularWebpackConfig, options)
> 
> // Feel free to modify this webpack config however you'd like to
> return singleSpaWebpackConfig
> }`
> 
> Thanks for the help!
how did you managed to do so? I repeated your step but keep getting this error

zone.min.js:13 Uncaught Error: systemjs-webpack-interop: There is no such module 'mf-images' in the SystemJS registry. Did you misspell the name of your module?
