### ISSUE TITLE
Setting `libraryName` via `architect.build.options` fails with error

### ISSUE THREAD

**Issue by Den-dp** [CanopyTax/single-spa-angular#119]
When trying to set `libraryName` via `angular.json` (as per https://single-spa.js.org/docs/ecosystem-angular/#use-angular-builder)
```
{
  "architect": {
      "build": {
        "builder": "single-spa-angular:build",
        "options": {
          "libraryName": "hello",
        }
      },
      "serve": {
        "builder": "single-spa-angular:dev-server",
        "options": {
        }
      }
  }
}
```
I see the following error:
```
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(libraryName).
```
--------------

Just to workaround it I also tried to override it in `extra-webpack.config.js` by passing options into `singleSpaAngularWebpack()` but found that this function do not use the second argument (see discussion https://github.com/CanopyTax/single-spa-angular/commit/52f55ce62e831274d0df05639f15b7b8e0580f27#comments )

So as a temporary solution I end up with directly tinkering webpack config:
```
singleSpaWebpackConfig.output.library = 'myAppName';
```

**Comment by joeldenning** [comment]
Are you using Angular 7 or Angular 8?

If Angular 8, note that the single-spa-angular custom builder doesn't work and you should follow [these instructions](https://single-spa.js.org/docs/ecosystem-angular#angular-8) which set you up with [`@angular-builders/custom-webpack`](https://www.npmjs.com/package/@angular-builders/custom-webpack)

**Comment by Den-dp** [comment]
@joeldenning my bad then. I initially thought that `"options": { "libraryName": "hello" }` support should be possible even for Angular 8 (and @angular-builders/custom-webpack).

**Comment by joeldenning** [comment]
No it's only for the Angular 7 builder. For overriding webpack config in Angular 8, you can modify it inside of [`extra-webpack.config.js`](https://github.com/joeldenning/coexisting-angular-microfrontends/blob/master/app1/extra-webpack.config.js)
