### ISSUE TITLE
Angular app bootstrapped with platformBrowserDynamic bundles compiler.js

### ISSUE THREAD

**Issue by clpalmer** [CanopyTax/single-spa-angular#12]
Been trying to dive through this for some time now, but running into a bit of a dead end, as my deep understanding of some of this stuff is limited.

My bundle size is getting rather large, and a huge chunk of it is Angular's compiler. This seems to only be required because I'm using platformBrowserDynamic instead of platformBrowser. If I flip that over, it drops out and ends up being 460+kB smaller parsed size (115+kB gzipped), which is a significant change.

However, without that, it's not actually working as single-spa states the angularPlatform should be platformBrowserDynamic. Is this a fundamental requirement or should I be able to use the AoT version?

**Comment by joeldenning** [comment]
Are you seeing an error when you pass in platformBrowser as the `angularPlatform`? I see that [we require an angularPlatform to be passed in](https://github.com/CanopyTax/single-spa-angular/blob/master/src/single-spa-angular.js#L22), but we definitely allow for a different platform than platformBrowserDynamic.

Also, if you could provide code samples and stacktraces, that might help me understand what issue you're seeing.

**Comment by clpalmer** [comment]
I think the issue is that for me, the fix (ie. getting compiler out of the bundle) is to use platformBrowser instead of platformBrowserDynamic. But for that, it requires bootstrapping via a different method. In single-spa-angular, it calls [bootstrapModule](https://github.com/CanopyTax/single-spa-angular/blob/10015c2d66157b06c99a9b866cdd2f8e940c3a72/src/single-spa-angular.js#L59) on the provided angularPlatform, but for platformBrowser, it would require calling bootstrapModuleFactory instead.

Again, though, this is based on my limited understanding of the entire process, obtained while trying to trim down my bundle size.

**Comment by clpalmer** [comment]
A tiny bit more info here: http://www.syntaxsuccess.com/viewarticle/ahead-of-time-compilation-in-angular-2.0 in the Bootstrapping section

**Comment by clpalmer** [comment]
@joeldenning - Had any time to look at this any further?

**Comment by joeldenning** [comment]
@clpalmer I'm looking into this now, as part of #31 -- thanks for linking me to those resources, i'll check them out and see what i can figure out.

**Comment by joeldenning** [comment]
I learned some more about this -- dead code elimination and tree shaking is not working which is what causes the bundle to be so huge. Likely because somehow we're using the [fesm5 version](https://github.com/angular/platform-browser-builds/blob/master/fesm5/platform-browser.js) of @angular/platform-browser-dynamic instead of [es2015 version](https://github.com/angular/platform-browser-builds/blob/master/esm2015/platform-browser.js). See https://twitter.com/Joelbdenning/status/1111390464685412352 for more info

**Comment by clpalmer** [comment]
I managed to get it to shake out the compiler without changes to your code, but had to hack it a bit and pass in a wrapper object that contains a function bootstrapModule that internally calls bootstrapModuleFactory on the platformBrowser object. I think it's probably be sufficient if you just checked for the existence of the two functions on the provided angularPlatform we pass in and call the appropriate one.

**Comment by joeldenning** [comment]
I just released single-spa-angular@3.0.0-beta.10, which has a change to how you call singleSpaAngular() such that angular can statically analyze the code and replace platformBrowserDynamic() with platformBrowser(). Bundle size on a hello world app went from 500kb to 250kb.

Want to try it out and let me know if it works for you? See https://github.com/CanopyTax/single-spa-angular/releases/tag/v3.0.0-beta.10

**Comment by joeldenning** [comment]
I'm closing this, since it is fixed with #43. Feel free to ask further questions or reopen if 3.0.0-beta.10 doesn't work for you

**Comment by clpalmer** [comment]
Thanks @joeldenning! Working nicely. Same bundle size as my hack-around wrapper function before, but eliminates the warning about no bootstrap in main module.

**Comment by joeldenning** [comment]
Awesome, happy to hear this 👍
