### ISSUE TITLE
Export unregisterApplication method with SingleSpa object

### ISSUE THREAD

**Issue by varora1406** [CanopyTax/single-spa-angular#124]
I am working on a project to fullfil my need for unregistering application in 1 language, and registering again in 2nd language.

I see unregisterApplication method implementation, it's available in SingleSpa and will work for my requirement

**Comment by joeldenning** [comment]
The unregisterApplication api is intentionally only exposed to the single-spa devtools. Using it would be an antipattern, and so we do not allow it.

> I am working on a project to fullfil my need for unregistering application in 1 language, and registering again in 2nd language.

Could you help me understand what you mean here? The only language that works in the browser is javascript. Are you talking about different frameworks?

Could you please explain what you're trying to accomplish? I am very confident that it can be done without the use of unregisterApplication.

**Comment by varora1406** [comment]
We have differenr build in Angular for i18n (Internationalization).
If user switch language (from English to something else), I required to switch Application build.

But I figured now, unloadApplication, changing URL of build, and loading again has helped me in achieving it

**Comment by joeldenning** [comment]
Yes, you can unloadApplication, clear out the module from the SystemJS registry, and that should work, too.
