### ISSUE TITLE
allow configuration of externals

### ISSUE THREAD

**Issue by cgatian** [CanopyTax/single-spa-angular#21]
Allow the builder to be configured to support marking certain libraries as external.  These are then mapped to Webpack's [externals](https://webpack.js.org/configuration/externals/) configuration.

This would be useful for commonly used libraries like zonejs and [hammerjs](https://hammerjs.github.io/)

**Comment by joeldenning** [comment]
This can now be accomplished using a partial webpack config that is merged into the final config (#40).
