### ISSUE TITLE
Angular Application don't load assets/fonts

### ISSUE THREAD

**Issue by mncorreia** [CanopyTax/single-spa-angular#394]
**Describe the bug or question**

Hello there. In my angular app with single spa I can't get assets/fonts.

**To Reproduce**
In root application:
```html
<script type="systemjs-importmap">
  {
    "imports": {
      "root-config": "//localhost:9000/root-config.js",
      "myapp": "http://localhost:4200/main.js"
    }
  }
</script>

```

 

In angular app (myapp):

angular.json

```json

.
.
.
"myapp": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "outputPath": "dist/myapp",
            "index": "src/index.html",
            "main": "src/main.single-spa.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.single-spa.json",
            "aot": true,
            "assets": [
              "src/favicon.ico",
              "src/assets",
              {
                "glob": "**/*",
                "input": "node_modules/design-system/src/lib/@theme/styles/fonts",
                "output": "/assets/fonts"
              }
            ],
            "styles": [
              "node_modules/@fortawesome/fontawesome-free/css/all.css",
              "node_modules/design-system/src/lib/@theme/styles/styles.scss",
              "node_modules/pace-js/templates/pace-theme-flash.tmpl.css",
              "src/styles.scss"
            ],
            "scripts": [
              "node_modules/pace-js/pace.min.js"
            ],
            "customWebpackConfig": {
              "path": "extra-webpack.config.js",
              "libraryName": "myapp",
              "libraryTarget": "umd"
            }
          },

.

.

.

```

 

styles.scss:
```scss

@font-face {
  font-family: "Moderat";
  src: url("/assets/fonts/Moderat-Light.woff2") format("woff2"),
    url("/assets/fonts/Moderat-Light.woff") format("woff"),
    url("/assets/fonts/Moderat-Light.ttf") format("truetype");
  font-weight: 300;
  font-style: normal;
}

```

 

Running with:

`ng serve myapp --disable-host-check --port 4200 --deploy-url http://localhost:9000/ --live-reload false`

 

my fonts is located in"node_modules/design-system/src/lib/@theme/styles/fonts":

 

 

**Expected behavior**

In root config, my angular app loaded with fonts as imported at styles.scss (myapp).

 

**Screenshots and/or console output**

GET http://localhost:9000/assets/fonts/Moderat-Light.woff2 net::ERR_ABORTED 404 (Not Found)       

GET http://localhost:9000/assets/fonts/Moderat-Light.woff net::ERR_ABORTED 404 (Not Found)

GET http://localhost:9000/assets/fonts/Moderat-Light.ttf net::ERR_ABORTED 404 (Not Found)

**Comment by JOJYV** [comment]
> **Describe the bug or question**
> 
> Hello there. In my angular app with single spa I can't get assets/fonts.
> 
> **To Reproduce** In root application:
> 
> ```
> <script type="systemjs-importmap">
>   {
>     "imports": {
>       "root-config": "//localhost:9000/root-config.js",
>       "myapp": "http://localhost:4200/main.js"
>     }
>   }
> </script>
> ```
> 
> In angular app (myapp):
> 
> angular.json
> 
> ```json
> .
> .
> .
> "myapp": {
>       "projectType": "application",
>       "schematics": {
>         "@schematics/angular:component": {
>           "style": "scss"
>         }
>       },
>       "root": "",
>       "sourceRoot": "src",
>       "prefix": "app",
>       "architect": {
>         "build": {
>           "builder": "@angular-builders/custom-webpack:browser",
>           "options": {
>             "outputPath": "dist/myapp",
>             "index": "src/index.html",
>             "main": "src/main.single-spa.ts",
>             "polyfills": "src/polyfills.ts",
>             "tsConfig": "tsconfig.single-spa.json",
>             "aot": true,
>             "assets": [
>               "src/favicon.ico",
>               "src/assets",
>               {
>                 "glob": "**/*",
>                 "input": "node_modules/design-system/src/lib/@theme/styles/fonts",
>                 "output": "/assets/fonts"
>               }
>             ],
>             "styles": [
>               "node_modules/@fortawesome/fontawesome-free/css/all.css",
>               "node_modules/design-system/src/lib/@theme/styles/styles.scss",
>               "node_modules/pace-js/templates/pace-theme-flash.tmpl.css",
>               "src/styles.scss"
>             ],
>             "scripts": [
>               "node_modules/pace-js/pace.min.js"
>             ],
>             "customWebpackConfig": {
>               "path": "extra-webpack.config.js",
>               "libraryName": "myapp",
>               "libraryTarget": "umd"
>             }
>           },
> 
> .
> 
> .
> 
> .
> ```
> 
> styles.scss:
> 
> ```css-scss
> @font-face {
>   font-family: "Moderat";
>   src: url("/assets/fonts/Moderat-Light.woff2") format("woff2"),
>     url("/assets/fonts/Moderat-Light.woff") format("woff"),
>     url("/assets/fonts/Moderat-Light.ttf") format("truetype");
>   font-weight: 300;
>   font-style: normal;
> }
> ```
> 
> Running with:
> 
> `ng serve myapp --disable-host-check --port 4200 --deploy-url http://localhost:9000/ --live-reload false`
> 
> my fonts is located in"node_modules/design-system/src/lib/@theme/styles/fonts":
> 
> **Expected behavior**
> 
> In root config, my angular app loaded with fonts as imported at styles.scss (myapp).
> 
> **Screenshots and/or console output**
> 
> GET http://localhost:9000/assets/fonts/Moderat-Light.woff2 net::ERR_ABORTED 404 (Not Found)
> 
> GET http://localhost:9000/assets/fonts/Moderat-Light.woff net::ERR_ABORTED 404 (Not Found)
> 
> GET http://localhost:9000/assets/fonts/Moderat-Light.ttf net::ERR_ABORTED 404 (Not Found)

I am also getting the same issue. Tried in different ways. Could not find any solutions .I think the only solution is to set the  webpack_public path in assetUrl function .Any way I am not able to fix it. It is road blocking issue. Could not find any code snippet for angular to deal with this

Useful Url :https://webpack.js.org/guides/public-path/#root

**Comment by JOJYV** [comment]
I am also getting the same issue. Tried in different ways. Could not find any solutions .I think the only solution is to set the webpack_public path in assetUrl function .Any way I am not able to fix it. It is road blocking issue. Could not find any code snippet for angular to deal with this

Useful Url :https://webpack.js.org/guides/public-path/#root

**Comment by JOJYV** [comment]
> I'm transferring this to single-spa-angular. I don't spend much time maintaining single-spa-angular and there aren't many that help there, so I don't think you'll get a response quickly. I suggest reading https://single-spa.js.org/docs/ecosystem-angular#angular-assets

Could you find any update on this

**Comment by OriolInvernonLlaneza** [comment]
> I am also getting the same issue. Tried in different ways. Could not find any solutions .I think the only solution is to set the webpack_public path in assetUrl function .Any way I am not able to fix it. It is road blocking issue. Could not find any code snippet for angular to deal with this

I had the same problem and also couldn't get public_path working. Our workaround was to load the font in the root HTML.

**Comment by arturovt** [comment]
Hey, I know it's been long since this issue is opened. It's a pity that Webpack doesn't parse `__webpack_public_path__` within CSS files, that would be easy just to write something like `url(__webpack_public_path__/assets/some_font.woff2)`.

I've added an example into master on how to load fonts: https://github.com/single-spa/single-spa-angular/commit/3f7ae764c9e021e9e7a69f5a75a3fc513965fd93

You can also load it via `style` element and not via the `FontFace`:

```ts
function loadMontserrat(): void {
  const id = 'montserrat';
  if (document.getElementById(id) !== null) {
    return;
  }
  const style = document.createElement('style');
  style.innerHTML = `
  @font-face {
    font-family: 'Montserrat';
    src: url(${assetUrl('/path-to-font.woff2')}) format('woff2');
  }
`;
  style.id = id;
  document.head.appendChild(style);
}
```

**Comment by pparavicini** [comment]
I had the same issue, and used the less sophisticated approach of copying the fonts in the 'public' directory of the root-config single-spa project, from which Webpack serves static assets  in a local env.  It seems to work fine.

In a QA/production environments,  you would have to make the fonts available in the same equivalent static folder.

I am relatively new to single-spa (and angular), so take it with a grain of salt.
