### ISSUE TITLE
Angular 7 load multiple app

### ISSUE THREAD

**Issue by HemendPatel63** [CanopyTax/single-spa-angular#42]
awesome will get support to angular 7.

I was going through the instruction and start loading my applications. I am able to build and load the application through index.html but it load only single application base on base href. 

https://github.com/CanopyTax/single-spa-angular/blob/master/README.md

I am new to single-spa so not sure what are the options to register multiple application:
 singleSpa.registerApplication('spa1', window.spa1.default, location => true);
 singleSpa.registerApplication('spa2', window.spa2.default, , location => location.pathname.indexOf("/spa2") >= 0);

**Comment by HemendPatel63** [comment]
fond a solution

**Comment by joeldenning** [comment]
👍 see related #41
