### ISSUE TITLE
Documentation and/or schematics for changing `app-root` to something unique

### ISSUE THREAD

**Issue by joeldenning** [CanopyTax/single-spa-angular#51]
When you have 2+ angular apps on the page, you can't have both of the root components have the `app-root` selector -- otherwise angular doesn't know which one is which.

So you need to change the name of your root component in each app in two places:
(1) The singleSpaAngular `template` opt. https://github.com/joeldenning/coexisting-angular-microfrontends/blob/49d544860518b6f476e5aeb029071901bd180dab/app1/src/main.single-spa.ts#L16
(2) The component selector inside of app.component.ts. https://github.com/joeldenning/coexisting-angular-microfrontends/blob/49d544860518b6f476e5aeb029071901bd180dab/app1/src/app/app.component.ts#L4

We should at least add documentation for this, or maybe explore schematics for it.

**Comment by StephenRansom** [comment]
It'd be great to have a schematic that updated references for app-root to projectname-root or similar, but in the meantime I added some documentation https://github.com/CanopyTax/single-spa-angular/pull/54

**Comment by joeldenning** [comment]
This actually is the `--prefix` option with `ng new`. See the documentation for it here: https://github.com/CanopyTax/single-spa-angular#configuring-multiple-apps
