### ISSUE TITLE
Assets in angular.json are not being loaded 

### ISSUE THREAD

**Issue by joeldenning** [CanopyTax/single-spa-angular#59]
<img width="357" alt="Screen Shot 2019-04-17 at 1 13 14 PM" src="https://user-images.githubusercontent.com/5524384/56314530-95ad9f00-6112-11e9-876e-540d51ff3769.png">

<img width="349" alt="Screen Shot 2019-04-17 at 1 12 18 PM" src="https://user-images.githubusercontent.com/5524384/56314538-99d9bc80-6112-11e9-864f-6303bfbbf1ee.png">

**Comment by DanielNetzer** [comment]
I Actually managed to solve this issue by adding to all the assets path the relative to the new dist, e.g. `./appName/dist/projectName/assets/...`

**Comment by liuyiba** [comment]
Yes, I also reproduce this issue. And @DanielNetzer your solution works for me.

**Comment by joeldenning** [comment]
Could you provide examples of how you're using assets? Are these images that you want to reference via `<img src="/dist/projectName/assets/my-img.png">`? Fonts? Something else?

What I am most interested in is how you're using them in your components.

**Comment by joeldenning** [comment]
cc @StephenRansom

**Comment by liuyiba** [comment]
I also found this issue when I retriving apps from another domain.
For example the app2 is a child application under parent app. My parent app is serve at 4200 port. the app2 is serve at 3200 port. The image will show when I visit http://localhost:3200/app2 directly. But when I visit http://localhost:4200/app2 the image will missing. The error like this 
![image](https://user-images.githubusercontent.com/17810361/56416107-76557400-62c2-11e9-8f84-e9bf9e4e7d62.png)

It seems will go to the parent server to look for the image, so will get 404 error. 
I use <img src="./app2/dist/app2/assets/images/map.png" alt="123"> to show the image on app2. How to fix this? what's the best practice for the image and the css or third party in assets?

**Comment by StephenRansom** [comment]
References like `background-image: url("some/image/location");` and <img src="/some/image/location">caused 404s when the app was being served.  Fonts referenced by my widget factory (prime-ng) were also lost. They got dumped into dist/appname, but requests for them returned 404s. I was able to fix the issue by adding the deploy url to the build script, and I set the webpack public path (which also allowed me to load my other js chunks as well)

**Comment by DanielNetzer** [comment]
> and I set the webpack public path (which also allowed me to load my other js chunks as well)
@StephenRansom can you elaborate more on how you achieved that? and I assume you are talking about lazy loaded modules inside your angular app.

**Comment by joeldenning** [comment]
Hmm, I'm thinking this one over in the context of both local envs and deployed envs, with SystemJS coordinating the loading of modules. And I'm not thinking of  a graceful solution. The main solution in situations similar to these is to import the assets and have webpack bundle them, and then use webpack public path to ensure that the bundles are downloaded at the correct url.

But in this case, angular's assets.json are not bundled by webpack and so having a dynamic download url for a SystemJS bundle will result in the assets not being loaded  correctly in all situations.

🤔 I'll have to think this one over -- might have to declare this a limitation of using single-spa and angular together the default/normal way, with only the adventurous pursuing their own way of doing it.

**Comment by StephenRansom** [comment]
@DanielNetzer To set the webpack public path, at the top of your main.single-spa.ts you can put `__webpack_public_path__ = 'Path/To/Assets/dist/whatever';`

similarly you can add a deploy url to your build script in the package.json with `--deployUrl=PathTo/appname/dist/whatever`

This can function as a workaround until a more elegant solution is found.

**Comment by joeldenning** [comment]
Here's a solution that works for this. I'm open to ideas to making this easier, but I'll post this here as a solution and close this issue for now

app.component.html ([example](https://github.com/joeldenning/coexisting-angular-microfrontends/blob/master/app1/src/app/app.component.html#L9))
```html
<img src="{{assetsBase}}/assets/yoshi.png" />
```

app.component.ts ([example](https://github.com/joeldenning/coexisting-angular-microfrontends/blob/master/app1/src/app/app.component.ts#L11))
```ts
import { Component } from '@angular/core';

@Component({
  selector: 'app1-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  // @ts-ignore
  assetsBase = __webpack_public_path__;
}
```

main.single-spa.ts ([example](https://github.com/joeldenning/coexisting-angular-microfrontends/blob/d4ceffb3bcbefa50027c4dcc91bd93158695dc6b/app1/src/main.single-spa.ts#L1))
```ts
// have this import at the very top
import './set-public-path'
```

set-public-path.ts ([example](https://github.com/joeldenning/coexisting-angular-microfrontends/blob/master/app1/src/set-public-path.ts#L2))
```ts
// Replace with your port number
// @ts-ignore
__webpack_public_path__ = 'http://localhost:4201/'
```

**Comment by joeldenning** [comment]
I have found a good strategy for this. The best way to load assets with single-spa is now described in https://github.com/CanopyTax/single-spa-angular#angular-assets. See related #85

**Comment by joeldenning** [comment]
See new documentation for this at https://single-spa.js.org/docs/ecosystem-angular.html#angular-assets

**Comment by jimmyhdolores** [comment]
As they do in the case that Image by Sass is loaded for example

.body-row {

background: url ("/ assets / images / myimage.jpg") without repetition bottom right;
}

I set the setPublicPath but keep throwing 404

**Comment by joeldenning** [comment]
Hi @jimmyhdolores, good question. CSS and Sass that call `url()` need to include the [webpack public path](https://webpack.js.org/guides/public-path/#root) as the prefix to their URLs. In the context of Angular, the webpack public path is referred to as the "deploy url" / `--deploy-url`.

For single-spa-angular, the [`assetUrl` function](https://single-spa.js.org/docs/ecosystem-angular#angular-assets) helps with calculating a full URL that includes the webpack public path. The documentation I just linked to shows how to use the assetUrl function in both typescript and HTML templates, but it does not show how to do it in CSS/Sass files. The string inside of `url()` is processed by webpack and I have a few guesses as to approaches that might work. Could you confirm if any of the below options work for you?

#### Option 1 - relative paths

```css
.body-row {
  /* Use a relative path for myimage.jpg. Adjust the ../.. to make it correctly refer to the assets directory in your project*/
  background: url ("../../assets/images/myimage.jpg") without repetition bottom right;
}
```

#### Option 2 - direct use of webpack public path

```css
.body-row {
  background: url (__webpack_public_path__ + "/assets/images/myimage.jpg") without repetition bottom right;
}
```

Let me know if either of those work - if they do we should add it to the official docs.

**Comment by Abhishek-Kanitkar** [comment]
I am trying to migrate an existing Angular 10 project to single spa micro frontend.

My image urls in .scss files are trying to point to the root application than the micro app.

background: url('/assets/images/login_bg.png') no-repeat center center fixed;

Can you please help in resolving this issue ?

What is concrete solution for this ?

rebaseRootRelativeCssUrls is now deprecated  ;(

@StephenRansom  @joeldenning  can you please kindly help in this ?

How to make sure that the images in SASS files keep pointing to the micro frontend rather than the root application.

**Comment by joeldenning** [comment]
I can provide no guidance here, as I don't know Angular very well

**Comment by zalito12** [comment]
Hi! In case anyone has reached this issue with no solution, option 1 from @joeldenning works well for local development:
````
.body-row {
  /* Use a relative path for myimage.jpg. Adjust the ../.. to make it correctly refer to the assets directory in your project*/
  background: url ("../../assets/images/myimage.jpg") without repetition bottom right;
}
````

But after build if you are using ``--deploy-url`` different from root, like me, webpack generates assets twice and the final url on css is not well calculated. As  I'm using pure css the only solution I found was to add a string replacer for webpack css loaders
````
.body-row {
  /* Use a relative path for myimage.jpg. Adjust the ../.. to make it correctly refer to the assets directory in your project*/
  background: url ("__webpack_public_path__/assets/images/myimage.jpg") without repetition bottom right;
}
````
````
const webpackMerge = require('webpack-merge');
const StringReplacePlugin = require('string-replace-webpack-plugin');

[...]

  const cssLoader = {
    module: {
      rules: [
        {
          test: /\.css$/,
          use: [{ loader: getCssReplacement(singleSpaWebpackConfig.output.publicPath) }]
        }
      ]
    }
  };
const mergedConfig = webpackMerge.smart(singleSpaWebpackConfig, cssLoader);

[...]

getCssReplacement = (publicPath) => {
  return (replaceCssAssetsUrl = StringReplacePlugin.replace({
    replacements: [
      {
        pattern: /__webpack_public_path__/g,
        replacement: function (_match, _p1, _offset, _string) {
          return publicPath;
        }
      }
    ]
  }));
};
````
I will update comment with code reference when I push my repo.

**Comment by larsf96** [comment]
@zalito12 Can you please provide the code reference? Would be very helpful

**Comment by RuBAN-GT** [comment]
Hi everyone,
I have the other one case with static js file (workers):

```json
[
  "src/favicon.ico",
  "src/assets",
  {
    "glob": "**/*.worker.js",
    "input": "./node_modules/my-caclulation-lib/dist/bundle/",
    "output": "."
  }
]
```

As you can see `my-caclulation-lib` has js worker files (they're complied by https://github.com/GoogleChromeLabs/worker-plugin on the library side). Does somebody have a way to provide a proper path/url to these workers as well?

**Comment by Yurii-Yanovitsky** [comment]
How would you implement loading assets with single-spa-react app? Is it still using the webpack public path? How to do it in more elegant way?

**Comment by ninjabhishek** [comment]
@zalito12 when I tried your solution, it said webpackMerge.smart is not a function. Using webpack 4. merge function fails to do the required. any idea on how to solve this?

**Comment by zofip** [comment]
> See new documentation for this at https://single-spa.js.org/docs/ecosystem-angular.html#angular-assets

Excelente documentación. Gracias !!! 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 🥇

**Comment by Alessandroinfo** [comment]
I still

> I also found this issue when I retriving apps from another domain. For example the app2 is a child application under parent app. My parent app is serve at 4200 port. the app2 is serve at 3200 port. The image will show when I visit http://localhost:3200/app2 directly. But when I visit http://localhost:4200/app2 the image will missing. The error like this ![image](https://user-images.githubusercontent.com/17810361/56416107-76557400-62c2-11e9-8f84-e9bf9e4e7d62.png)
> 
> It seems will go to the parent server to look for the image, so will get 404 error. I use ![123](./app2/dist/app2/assets/images/map.png) to show the image on app2. How to fix this? what's the best practice for the image and the css or third party in assets?

I still have this issue.

The only solution i found it's to put the `deployUrl` in `angular.json` or `publicPath` in webpack config pointing to the correct url (`http://localhost:3200` for example).
Another solution is to put all the assets in the root-config repository an tell webpack to copy those on the dist.

But those are not solutions, are only temporary fixes.

Can @joeldenning give hint about those global styles imported in the `angular.json` that don't resolve the path correctly?

**Comment by michaelchambaud-eaton** [comment]
@Alessandroinfo Have you ever found a solution?

**Comment by zalito12** [comment]
Hi! I forgot about this, I got this working and running. You can check the repo: https://github.com/zalito12/Portfolio/tree/master/home

This was my extra webpack conf at the end:

```
const singleSpaAngularWebpack = require("single-spa-angular/lib/webpack")
  .default;
const webpackMerge = require("webpack-merge");

module.exports = (angularWebpackConfig, options) => {
  const singleSpaWebpackConfig = singleSpaAngularWebpack(
    angularWebpackConfig,
    options
  );

  singleSpaWebpackConfig.externals.push(
    "rxjs",
    "rxjs/operators",
    /^@gongarce\/api$/
  );

  singleSpaWebpackConfig;

  const library = {
    output: {
      library: "portfolio-home",
    },
  };

  const cssLoader = {
    module: {
      rules: [
        {
          test: /\.css$/,
          loader: "string-replace-loader",
          options: {
            search: /__webpack_public_path__/g,
            replace: singleSpaWebpackConfig.output.publicPath,
          },
        },
      ],
    },
  };

  const mergedConfig = webpackMerge.merge(
    singleSpaWebpackConfig,
    library,
    cssLoader
  );

  return mergedConfig;
};
```

And like this in the css:

`background-image: url("__webpack_public_path__/assets/images/stars.svg");`

**Comment by beardedprince** [comment]
How can I load assets that should be added to angular.json? Since Single SPA doesn't load scripts in angular.json 
https://single-spa.js.org/docs/ecosystem-angular/#angular-assets
