### ISSUE TITLE
IE11 router not working

### ISSUE THREAD

**Issue by kbjerke** [CanopyTax/single-spa-angular#61]
Hi, this is a follow-up of #56.

With coexisting-angular-microfrontends as base, I made the following changes to index.html:
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Angular app</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <base href="/" />
</head>
<body>
  <script src="https://unpkg.com/core-js-bundle@3.0.1/minified.js"></script>
  <script src="https://unpkg.com/zone.js"></script>
  <script src="https://unpkg.com/single-spa@4.3.0/lib/umd/single-spa.min.js"></script>
  <script src="/navbar/dist/navbar/main.js"></script>
  <script src="/app1/dist/app1/main.js"></script>
  <script src="/app2/dist/app2/main.js"></script>
  <script>
    singleSpa.registerApplication('navbar', window.navbar.default, function() { return true; });
    singleSpa.registerApplication('app1', window.app1.default, function(location) { return location.pathname.startsWith('/app1'); });
    singleSpa.registerApplication('app2', window.app2.default, function(location) { return location.pathname.startsWith('/app2'); });
    singleSpa.start();
  </script>
</body>
</html>
```

At root, it doesn't render the NavbarComponent, it just has a router-outlet:
![image](https://user-images.githubusercontent.com/35374983/56568954-54a50700-65b8-11e9-8c72-8d90a157fd4b.png)

And from the console I find the error:
`Unhandled Navigation Error: `
With no stacktrace or message.

So I added the enableTracing option to the navbar app's Router:
```
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { NavbarComponent } from './navbar/navbar.component';

const routes: Routes = [
  {path: '**', component: NavbarComponent},
];

@NgModule({
  imports: [RouterModule.forRoot(routes, { enableTracing: true })],
  exports: [RouterModule]
})
export class AppRoutingModule { }
```
![image](https://user-images.githubusercontent.com/35374983/56569262-e876d300-65b8-11e9-9c3b-20dae1caa8ca.png)

And diffing from Chrome:
![image](https://user-images.githubusercontent.com/35374983/56570132-a484cd80-65ba-11e9-8d3b-16cc75fa8f37.png)

 It seems to crash at ResolveEnd? And the RoutesRecognized event doesn't return a component.

**Comment by joeldenning** [comment]
Hi @kbjerke, single-spa@4.3.0 introduced a bug in IE11 support (https://github.com/CanopyTax/single-spa/issues/299) that was fixed in https://github.com/CanopyTax/single-spa/pull/300 and released in https://github.com/CanopyTax/single-spa/releases/tag/v4.3.2.

Could you confirm if your issue still occurs after upgrading to single-spa@4.3.2?

**Comment by kbjerke** [comment]
Hi @joeldenning this works perfectly. Probably should've thought of checking the other dependencies... Sorry about that.

Can I suggest adding updating:
[coexisting-angular-microfrontends/index.html](https://github.com/joeldenning/coexisting-angular-microfrontends/blob/master/index.html)
to reflect the change? :)

**Comment by joeldenning** [comment]
👍 glad it worked for you.

Pull requests are definitely accepted for coexisting-angular-microfrontends. I update it pretty regularly but sometimes it falls slightly behind. I plan on making a big improvement to  it in the next week or so and so i'll upgrade it then if it hasn't been fixed by that time.
