### ISSUE TITLE
HttpErrorResponse return status code 0 and description "Unknown Error"

### ISSUE THREAD

**Issue by HemendPatel63** [CanopyTax/single-spa-angular#75]
I have implemented HttpInterceptor to log service exception and noticed that it's always give the status code 0 and statusText description"Unknown Error" as we are getting XHR value null and it will return the default value set while calling the base function (  **_super.call(this, init, 0, 'Unknown Error')** ).

var HttpErrorResponse = /** @class */ (function (_super) {
    Object(tslib__WEBPACK_IMPORTED_MODULE_0__["__extends"])(HttpErrorResponse, _super);
    function HttpErrorResponse(init) {
        debugger;
        var _this = 
        // Initialize with a default status of 0 / Unknown Error.
        _super.call(this, init, 0, 'Unknown Error') || this;
        _this.name = 'HttpErrorResponse';
        /**

![image](https://user-images.githubusercontent.com/49240619/57951112-ce29cf80-78ae-11e9-81b8-8ebb48cf8178.png)

![image](https://user-images.githubusercontent.com/49240619/57951071-b18d9780-78ae-11e9-8eec-14f9c8afabc0.png)

**Comment by joeldenning** [comment]
I don't think this is related to single-spa-angular. Am closing for now, feel free to reopen if it is caused or related to single-spa or single-spa-angular.
