### ISSUE TITLE
localization issue using i18n 

### ISSUE THREAD

**Issue by HemendPatel63** [CanopyTax/single-spa-angular#76]
I am trying to implement localization using angular i18n tool. This tool use -- baseHref /language code/ to manage the navigation to specific language. In our single spa design, we are using common html file without baseHref.
Also we have multiple apps and are use APP_BASE_HREF to bootstrap the specific app.
providers: [{ provide: APP_BASE_HREF, useValue: '/app1/' },

I have tried to specify the basehref in our common index.html and it is loading the app but routing is not working.
Let me know is there any option to udpate the common basehref ?

**Comment by joeldenning** [comment]
Hmm I'll have to think about that one. Using the base href for i18n is a pretty odd choice by Angular. I don't have time to look into this deeply right now, but will look at this in the next week or two.

**Comment by HemendPatel63** [comment]
I have fixed this issue by setting APP_BASE_HREF value at build using angular.json configuration. Also I have created separate environment file for each language to support lazy loading and base_href value.

**Comment by aniketavhad** [comment]
In my case `assets/i18n/en.json' is failed to load from the particular app, Instead it is trying to search i18n into shell-app`. I am using `@ngx-translate/core` package to set locale and convert labels accordingly.

What will be the solution to load `en.json` from there respective app?

**Comment by joeldenning** [comment]
See https://single-spa.js.org/docs/ecosystem-angular#angular-assets, which explains the changes needed to properly load assets when using single-spa-angular

**Comment by murugan1992info** [comment]
@aniketavhad did you got any solution for that issue ?

**Comment by samir-kamble** [comment]
> In my case `assets/i18n/en.json` is failed to load from the particular app, Instead it is trying to search i18n into `shell-app`. I am using `@ngx-translate/core` package to set locale and convert labels accordingly.
> 
> What will be the solution to load `en.json` from there respective app?

I am also facing same problem. Have you found solution to it?

**Comment by JoaoEdu93** [comment]
> > In my case `assets/i18n/en.json` is failed to load from the particular app, Instead it is trying to search i18n into `shell-app`. I am using `@ngx-translate/core` package to set locale and convert labels accordingly.
> > What will be the solution to load `en.json` from there respective app?
> 
> I am also facing same problem. Have you found solution to it?

Same problem here. Any solution?

**Comment by murugan1992info** [comment]
Fixed.

For me I'm using interceptor for all the http calls, even this i18n request also processed through interceptor and the interceptor modifying our http request, So I add a check condition inside the interceptor to make sure it's not adding/changing any property of my i18n request.  Finally this is works for me!!!!.
