### ISSUE TITLE
Interapp communication with apps on different servers

### ISSUE THREAD

**Issue by ss00445018** [CanopyTax/single-spa-angular#81]
Hi, @joeldenning

I was trying to achieve inter app communication with my base as coexisting-angular-microfrontends (tried the example and it was very helpful).

I have 4-5 buttons on app1, and based on the users click, i would like the contents in app2 to populate accordingly. Just like the example both the apps are on different servers (4201, 4202).

Kindly assist with the approach to be followed.

**Comment by joeldenning** [comment]
Options:

1. **Use routes** (preferred solution). Have each of the buttons in app1 be `<a routerLink="/some-route"></a>`. Then in app2, use routes to control which content is rendered. This is by far the best solution, if it makes sense for your situation.


2. **Use ESM modules** to communicate.
In app2's single-spa.main.ts
```js
export function showContent(data) {
  // app1 calls this function that is defined in app2. Somehow get
  // app2 to use the `data` and render something with it
}
```


3. **Fire events**. You can either look for an npm library that does events, or just use the browser's built-in event system (which is what I usually do).

app1:
```js
window.dispatchEvent(new CustomEvent('app2-please-do-something', {
  detail: customDataForEvent
})
```

app2:
```ts
// create the event listener when your component mounts. Remove event listener when component
export class PeekABoo implements OnInit, OnDestroy {
  constructor(private logger: LoggerService) { }


  ngOnInit() {
    window.addEventListener('app2-please-do-something', this.doSomething)
  }

  ngOnDestroy() {
    window.removeEventListener('app2-please-do-something', this.doSomething)
  }

  doSomething(evt) {
    const customEventData = evt.detail
    // now do something with it to cause a re-render. Probably have to do ngZone.run() stuff
  }
}
```

Don't turn to Option 2 or Option 3 if you Option 1 is available to you. Option 1 is the best by far.
