### ISSUE TITLE
(Angular 8): Not able to build application

### ISSUE THREAD

**Issue by movimento** [CanopyTax/single-spa-angular#82]
I'm new to angular, and just trying to follow the Readme instructions...
but can't build the application.

**_$ ng build_**
Could not find the implementation for builder single-spa-angular:build
Error: Could not find the implementation for builder single-spa-angular:build
    at WorkspaceNodeModulesArchitectHost.resolveBuilder 

Somehow I think that the problem is with Angular and CLI  **8** support.  
But I want to keep using Angular 8 if possible...
Is single-spa limited up to Angular 7 ?

Thanks

**Comment by joeldenning** [comment]
Yeah single-spa-angular is not yet compatible with angular@8. Very much on the roadmap, though. I created https://github.com/CanopyTax/single-spa-angular/issues/83 to track overall progress.

**Comment by cleisommais** [comment]
I had the same issue, however, if you change the version only "@angular-devkit/build-angular" and "@angular/cli" devDependencies you will fix the issue. In my case, are 4 different Angular 8 projects with Material Design and Google Charts, after correct changes everything works fine.
The dependencies with the new version:

-     "@angular-devkit/build-angular": "~0.13.0",
-     "@angular/cli": "~7.3.6",

**Comment by joeldenning** [comment]
This is fixed in beta 27 and release candidate 0

https://github.com/CanopyTax/single-spa-angular/releases/tag/v3.0.0-rc.0
