### ISSUE TITLE
Angular 8 Support

### ISSUE THREAD

**Issue by joeldenning** [CanopyTax/single-spa-angular#83]
This issue is a master issue for all things for getting initial support of Angular 8

- [ ] https://github.com/CanopyTax/single-spa-angular/issues/52
- [ ] https://github.com/CanopyTax/single-spa-angular/issues/82

**Comment by WaBriones** [comment]
@joeldenning , just a question and a user of your single-spa-angular helper. We're currently on Angular 7 and have single-spa-angular for our microfrontend approach. With Angular 8, doesn't the dynamic loading of Angular 8 support what single-spa offers? Sorry, just a newbie question when it comes to micro frontends.

**Comment by joeldenning** [comment]
@WaBriones could you point me to some resources to read about the Angular 8 "dynamic loading"? Most of what I've read about Angular 8 has been related to Ivy Compiler, or also the stuff described [in this blog post](https://blog.angularindepth.com/embrace-yourself-angular-8-is-coming-1bf187c8f0bf)

**Comment by WaBriones** [comment]
Hey there, found it here: https://medium.com/@tomastrajan/why-and-how-to-lazy-load-angular-libraries-a3bf1489fe24

Unless I misunderstood the concept entirely.

**Comment by joeldenning** [comment]
Hey @WaBriones, thanks for the link. single-spa applications are closest to what the blog author calls "sub-applications". One big difference in implementation approach between what he encourages in the blog post vs what we do in single-spa is that single-spa does not require nor encourage a parent/child relationship between your single-spa applications, whereas "sub-applications" do require that. Additionally, sub-applications are not framework agnostic, whereas single-spa applications are framework agnostic and can exist alongside React or Vue apps. We don't use Angular to download the single-spa applications, but SystemJS.

Hopefully that clarifies some things for you -- appreciate you sharing that!

**Comment by WaBriones** [comment]
Right! I understand now, I forgot the main feature of single-spa is that its framework agnostic. So, if say we go the pure Angular route, would that negate the need for single-spa?

**Comment by joeldenning** [comment]
Going pure angular with single-spa offers some good things, including independent deployments for each of the single-spa applications, as well as separate git repos, separate build processes, etc. All within the same SPA.

Not sure if other angular solutions offer that kind of thing or not, but I think that using pure angular and single-spa together makes sense to gain those benefits. ^

**Comment by WaBriones** [comment]
With that, when do you think the support for Angular 8 will push through? :)

**Comment by joeldenning** [comment]
Your timing is great -- I worked on Angular 8 support yesterday and plan on continuing to do so today. I hope to finish Angular 8 support today, but don't really know if there will be unforeseen hurdles. I'm currently working on #82

**Comment by joeldenning** [comment]
Angular 8 is supported in [single-spa-angular@3.0.0-rc.0](https://github.com/CanopyTax/single-spa-angular/releases/tag/v3.0.0-rc.0)

**Comment by WaBriones** [comment]
Thank you so much Joel!
