### ISSUE TITLE
Single SPA Portal with multiple applications not working in IE11

### ISSUE THREAD

**Issue by rknash18** [CanopyTax/single-spa-angular#97]
We have a spa portal with multiple applications and its working in chrome and firefox but not in  IE.  please let me know we need to make any changes specific to IE browser.

single-spa-angular version : 3.0.0-beta.21

![image](https://user-images.githubusercontent.com/36893778/61913051-899b5f80-af01-11e9-9560-e8723b06b85d.png)

**Comment by joeldenning** [comment]
Hi @rknash18. Internet Explorer support is explained in https://single-spa.js.org/docs/ecosystem-angular.html#internet-explorer. That section of the docs should show you how to resolve this.

Closing for now but feel free to comment with further discussion
