### ISSUE TITLE
SPA Portal- Bootstrap styles

### ISSUE THREAD

**Issue by rknash18** [CanopyTax/single-spa-angular#99]
Bootstrap less files are overriding when navigating between applications in a spa portal.

when navigating from APP1 to APP2 , styles from APP1 are overriding the styles in APP2.

**Comment by joeldenning** [comment]
single-spa doesn't change the global nature of css rules, but there are many well established patterns for scoping your css to only one component at a time or within an application. For example, you can [scope your css](https://angular.io/guide/component-styles) with Angular, or you can wrap your applications in a div and then scope your css that way:

```
#app1 .my-class {
}
```
